FROM node:lts-bullseye
RUN apt-get update && apt-get install -y openssl ca-certificates
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY ./ ./
ENTRYPOINT ["npm", "start"]